# Generated by Django 4.1.7 on 2023-03-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipeingredient_recipeingredientfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='recipeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipeapp.rawrecipes'),
        ),
    ]
