# Generated by Django 4.1.7 on 2023-03-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_ingredient_remove_recipeingredient_ingredientname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recipeingredientfood',
            options={'managed': False},
        ),
    ]
