# Generated by Django 4.1.7 on 2023-03-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_ingredientsynonym_newingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessionNumber',
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
        migrations.DeleteModel(
            name='CompoundAlternateParent',
        ),
        migrations.DeleteModel(
            name='CompoundExternalDescriptor',
        ),
        migrations.DeleteModel(
            name='CompoundOntologyTerm',
        ),
        migrations.DeleteModel(
            name='CompoundsEnzyme',
        ),
        migrations.DeleteModel(
            name='CompoundsFlavor',
        ),
        migrations.DeleteModel(
            name='CompoundsHealthEffect',
        ),
        migrations.DeleteModel(
            name='CompoundsPathway',
        ),
        migrations.DeleteModel(
            name='CompoundSubstituent',
        ),
        migrations.DeleteModel(
            name='CompoundSynonym',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Enzyme',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodTaxonomy',
        ),
        migrations.DeleteModel(
            name='HealthEffect',
        ),
        migrations.DeleteModel(
            name='NcbiTaxonomyMap',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
        migrations.DeleteModel(
            name='OntologySynonym',
        ),
        migrations.DeleteModel(
            name='OntologyTerm',
        ),
        migrations.DeleteModel(
            name='Pathway',
        ),
        migrations.DeleteModel(
            name='PpRecipes',
        ),
        migrations.DeleteModel(
            name='PpUsers',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
